name: C++ Build & Runtime Checks + Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ valgrind

      - name: Build Bat-Computer
        run: g++ -std=c++20 -Wall -Wextra -O2 main.cpp -o batcomputer

      - name: Prepare input for non-interactive run
        run: |
          echo "0" > input.txt
          cat input.txt

      - name: Run executable with timeout
        run: |
          echo "Running batcomputer..."
          timeout 15s ./batcomputer < input.txt
          echo "Finished or timed out."

      - name: Runtime Checks
        uses: ./.github/actions/runtime_checks
        with:
          INPUT_FILENAME: input.txt
          EXECUTABLE_NAME: batcomputer
        timeout-minutes: 20
        continue-on-error: true

      - name: Run Valgrind
        run: |
          echo "Running Valgrind..."
          echo "0" > temp_input.txt
          timeout 15s valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes \
            ./batcomputer < temp_input.txt
          echo "Valgrind finished or timed out."
